<?php
/**
 * View
 *
 * Contains methods to render the output generated by Controller. This is used
 * by FrontController, which decides which View to use.
 *
 * User: Yraen Ironheart
 * Date: 1/11/11
 */
abstract class View {
	protected $template = null;
	protected $controllerData = null;

	/**
	 * Use this to get access to the controller's output.
	 * Controller output is stored in $this->controllerData
	 *
	 * @param $controllerData
	 * @param \Template $template
	 */
	public function __construct($controllerData, Template $template) {
		$this->setControllerData($controllerData);
		$this->setTemplate($template);
	}

	/**
	 * Set controller data
	 *
	 * @param  $controllerData
	 * @return void
	 */
	public function setControllerData($controllerData) {
		$this->controllerData = $controllerData;
	}

	/**
	 * Get controller data
	 *
	 * @return null
	 */
	public function getControllerData() {
		return $this->controllerData;
	}

	/**
	 * Set template
	 *
	 * @param Template $template
	 * @return void
	 */
	public function setTemplate(Template $template) {
		$this->template = $template;
	}

	/**
	 * Get template
	 *
	 * @return null
	 */
	public function getTemplate() {
		return $this->template;
	}

	/**
	 * Prints the processed template
	 */
	public function stdout() {
		echo $this->getTemplate()->getContent();
	}
}